### ISSUE TITLE
Error when trying to run sample code

### ISSUE THREAD

**Issue by Stephan811D** [WifWaf/TCA9548A#1]
If im trying to run your sample code I always get this error:

```
C:\Users\PC-Werkstatt\Documents\Arduino\libraries\TCA9548A\src\TCA9548A.cpp: In member function 'void TCA9548A::begin(uint8_t, uint8_t, TwoWire&)':

C:\Users\PC-Werkstatt\Documents\Arduino\libraries\TCA9548A\src\TCA9548A.cpp:18:34: error: no matching function for call to 'TwoWire::begin(uint8_t&, uint8_t&)'

 this->myWire->begin(_sda,_sdl);

In file included from C:\Users\PC-Werkstatt\Documents\Arduino\libraries\TCA9548A\src\TCA9548A.h:13:0,

from C:\Users\PC-Werkstatt\Documents\Arduino\libraries\TCA9548A\src\TCA9548A.cpp:9:

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:52:10: note: candidate: void TwoWire::begin()

void begin();
```

im using a arduino nano with the following pins:
```

#include "TCA9548A.h"
#define SCLPIN 5    // Your I2C pins
#define SDAPIN 4    // Your I2C pins

```
Do you have any idea?

**Comment by WifWaf** [comment]
Hi Stephan, sorry I missed this over a month ago.

I had only tested this library with the ESP32. Turns out, the Arduino Uno begin only accepts an address (for acting in slave mode), so adding I2C pins makes it throw an error.

I think is due to the Uno having only one set of I2C pins, so it assumes there's no need to add the additional argument.

It should be working now - though I imagine you've made past this library some time ago.

Cheers for the raising the issue,
